name: lb_game_internals
description: "A new Flutter package project."
version: 0.0.1
homepage:



environment:
  sdk: ^3.2.0

dependencies:
  audioplayers: ^6.0.0
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.5
  flutter_fortune_wheel: ^1.3.1
  logging: ^1.2.0
  meta: ^1.11.0
  provider: ^6.1.2
  shared_preferences: 2.2.2


dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  test: ^1.24.3

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/fonts/Permanent_Marker/PermanentMarker-Regular.ttf